import type { GraphData } from '@/types';

export const demoGraph: GraphData = {
  layout: 'dagre',
  nodes: [
    { id: 'f:src', type: 'folder', position: { x: 0, y: 0 }, data: { label: 'src', path: 'src' } },
    { id: 'f:core', type: 'folder', position: { x: 0, y: 0 }, data: { label: 'core', path: 'src/core' } },
    { id: 'f:ui', type: 'folder', position: { x: 0, y: 0 }, data: { label: 'ui', path: 'src/ui' } },
    { id: 'f:api', type: 'folder', position: { x: 0, y: 0 }, data: { label: 'api', path: 'src/api' } },
    { id: 'f:utils', type: 'folder', position: { x: 0, y: 0 }, data: { label: 'utils', path: 'src/utils' } },
    { id: 'file:index', type: 'file', position: { x: 0, y: 0 }, data: { label: 'index.ts', path: 'src/index.ts', extension: 'ts', fileClass: 'entry' } },
    { id: 'file:app', type: 'file', position: { x: 0, y: 0 }, data: { label: 'App.tsx', path: 'src/App.tsx', extension: 'tsx' } },
    { id: 'file:api:client', type: 'file', position: { x: 0, y: 0 }, data: { label: 'client.ts', path: 'src/api/client.ts', extension: 'ts' } },
    { id: 'file:api:routes', type: 'file', position: { x: 0, y: 0 }, data: { label: 'routes.ts', path: 'src/api/routes.ts', extension: 'ts' } },
    { id: 'file:core:auth', type: 'file', position: { x: 0, y: 0 }, data: { label: 'auth.ts', path: 'src/core/auth.ts', extension: 'ts' } },
    { id: 'file:core:db', type: 'file', position: { x: 0, y: 0 }, data: { label: 'db.ts', path: 'src/core/db.ts', extension: 'ts' } },
    { id: 'file:ui:button', type: 'file', position: { x: 0, y: 0 }, data: { label: 'Button.tsx', path: 'src/ui/Button.tsx', extension: 'tsx' } },
    { id: 'file:ui:nav', type: 'file', position: { x: 0, y: 0 }, data: { label: 'Navbar.tsx', path: 'src/ui/Navbar.tsx', extension: 'tsx' } },
    { id: 'file:utils:format', type: 'file', position: { x: 0, y: 0 }, data: { label: 'format.ts', path: 'src/utils/format.ts', extension: 'ts' } },
    { id: 'pkg:react', type: 'package', position: { x: 0, y: 0 }, data: { label: 'react', ecosystem: 'npm', version: '^19' } },
    { id: 'pkg:axios', type: 'package', position: { x: 0, y: 0 }, data: { label: 'axios', ecosystem: 'npm', version: '^1.6' } },
    { id: 'pkg:pg', type: 'package', position: { x: 0, y: 0 }, data: { label: 'pg', ecosystem: 'npm', version: '^8.11' } },
  ],
  edges: [
    { id: 'e1', source: 'f:src', target: 'f:core', type: 'contains' },
    { id: 'e2', source: 'f:src', target: 'f:ui', type: 'contains' },
    { id: 'e3', source: 'f:src', target: 'f:api', type: 'contains' },
    { id: 'e12', source: 'f:src', target: 'f:utils', type: 'contains' },
    { id: 'e4', source: 'f:src', target: 'file:index', type: 'contains' },
    { id: 'e5', source: 'f:src', target: 'file:app', type: 'contains' },
    { id: 'e6', source: 'f:api', target: 'file:api:client', type: 'contains' },
    { id: 'e7', source: 'f:api', target: 'file:api:routes', type: 'contains' },
    { id: 'e8', source: 'f:core', target: 'file:core:auth', type: 'contains' },
    { id: 'e9', source: 'f:core', target: 'file:core:db', type: 'contains' },
    { id: 'e10', source: 'f:ui', target: 'file:ui:button', type: 'contains' },
    { id: 'e11', source: 'f:ui', target: 'file:ui:nav', type: 'contains' },
    { id: 'e13', source: 'f:utils', target: 'file:utils:format', type: 'contains' },
    
    // Dependencies
    { id: 'd1', source: 'file:index', target: 'file:app', type: 'depends_on', animated: true },
    { id: 'd2', source: 'file:app', target: 'file:ui:nav', type: 'depends_on', animated: true },
    { id: 'd10', source: 'file:app', target: 'file:ui:button', type: 'depends_on', animated: true },
    { id: 'd3', source: 'file:ui:nav', target: 'file:core:auth', type: 'depends_on', animated: true },
    { id: 'd4', source: 'file:api:routes', target: 'file:core:auth', type: 'depends_on', animated: true },
    { id: 'd5', source: 'file:api:routes', target: 'file:core:db', type: 'depends_on', animated: true },
    { id: 'd11', source: 'file:api:routes', target: 'file:utils:format', type: 'depends_on', animated: true },
    { id: 'd6', source: 'file:api:client', target: 'pkg:axios', type: 'depends_on', animated: true },
    { id: 'd7', source: 'file:core:db', target: 'pkg:pg', type: 'depends_on', animated: true },
    { id: 'd8', source: 'file:ui:button', target: 'pkg:react', type: 'depends_on', animated: true },
    { id: 'd9', source: 'file:ui:nav', target: 'pkg:react', type: 'depends_on', animated: true },
    { id: 'd12', source: 'file:app', target: 'pkg:react', type: 'depends_on', animated: true },
  ],
};
